dist: xenial
sudo: false
language: python
matrix:
    fast_finish: true
python:
  - 3.6
  - 3.7
  - 3.8
install:
  - pip install -r extra/requirements.txt
  - pip install -r extra/requirements-test.txt
  - pip install coveralls
script:
  - pytest -v tests
after_success:
  - coveralls
branches:
  except:
    - /^play\/.*$/
