dist: xenial
language: python
matrix:
  fast_finish: true
python:
  - "3.6"
  - "3.7"
  - "3.8"
sudo: required

install:
  - pip install -r extra/requirements-test.txt
  - pip install .
  - pip install coveralls
script:
  - pytest -v tests
after_success:
  - coveralls
branches:
  except:
    - /^play\/.*$/
