sudo: false
language: python
cache:
    directories:
        - $HOME/.cache/pip
git:
    depth:
        - 1
matrix:
    allow_failures:
        python: 2.6
    fast_finish: true
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -r extra/requirements.txt
  - pip install -r extra/requirements-test.txt
  - pip install coveralls
script:
  - nose2 tests
after_success:
  - coveralls
branches:
  except:
    - /^play\/.*$/
