sudo: false
language: python
matrix:
    fast_finish: true
python:
  - 3.5
  - 3.6
install:
  - pip install -r extra/requirements.txt
  - pip install -r extra/requirements-test.txt
  - pip install coveralls
script:
  - pytest tests
after_success:
  - coveralls
branches:
  except:
    - /^play\/.*$/
